---
- name: 'Install kanidm-server and tools'
  hosts: 'kanidm-server'
  gather_facts: true
  become: true

  roles:
    - role: 'johanneskastl.install_one_or_more_packages'
      packages_to_be_installed:
        - kanidm-server
        - kanidm-clients
